### ISSUE TITLE
Level 3: CSS Selectors - Video & Challenges

### ISSUE THREAD

**Issue by birdcar** [GeneralOutcast/generaloutcast.github.io#6]
## Objective: Finish Level 3

_Note: Make sure to watch all of level three, there may be more than one video and set of challenges._
### Stuff You'll Need
- Focus
- The video on the Code School site
### To-Do
- [x] Complete the challenges. Create issues if you run into problems and label them "Question" if it's something you're confused about and "Stuck" if it's something you can't get past. 
- [x] Check this box, add the "Finished" label, and close this issue.

**Comment by sophanoph** [comment]
:frowning: so sad i don't have the old html guy anymore this new one is annoying and mind-numbingly boring

**Comment by birdcar** [comment]
@GeneralOutcast Yeah, I almost warned you. One of the CSS guys is awesome and the other CSS guy is rough. Just push through and you'll eventually get to the fun stuff.

**Comment by sophanoph** [comment]
:+1:
