### ISSUE TITLE
List items are tagged incorrectly

### ISSUE THREAD

**Issue by birdcar** [GeneralOutcast/generaloutcast.github.io#7]
Good job on getting the first bit of homework done in issue #3, but theres a bit of a problem with that code you committed. Namely, the list items are tagged incorrectly on all three lists.

All of the content is great! Just take a look over your tags and see if you can't catch your mistake.
## TO DO
- [x] Create a new branch off of master called `html-list-fix`
- [x] Edit the `index.html` file with the changes you think will resolve this issue.
- [x] Create a pull request from the `html-list-fix` branch to the master branch.
- [x] Title your pull request _"List items are supposed to be list items."_
- [x] In the body of the pull request, write up what changes you made and how you discovered the changes. (**bonus points**: see if theres a way to reference this issue so that it automatically closes once your pull request gets merged into master)
- [x] Assign the pull request to me, put it on the Front End Foundations milestone, and give it a label of "bugfix".
- [x] If you got it right, I'll merge the request; if not, I'll comment and give you some more instructions.

**Comment by sophanoph** [comment]
i don't know wtf  i'm doing

**Comment by birdcar** [comment]
@GeneralOutcast That's pretty impressive considering that you did it perfectly haha

**Comment by sophanoph** [comment]
okay well what did i do?!

**Comment by birdcar** [comment]
You did Github flow!
1. You made a branch so that you should safely commit a change
2. You used your resources to find the change that needed to be made, then edited the file and made a commit explaining the change.
3. You used a pull-request to resolve the issue that brought the need for the change to your attention
4. I took a look at your changes and merged them into master so that everything is all up to date.

Does that all make sense?

**Comment by sophanoph** [comment]
yeahh!! whoo-hoo! :100:  :+1:  :boom:  :exclamation:
